# Generated by Django 4.2.7 on 2025-10-12 13:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_options_and_more'),
        ('doctors', '0002_alter_doctor_options_and_more'),
        ('mappings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientdoctormapping',
            options={},
        ),
        migrations.RenameField(
            model_name='patientdoctormapping',
            old_name='assigned_date',
            new_name='created_at',
        ),
        migrations.AlterUniqueTogether(
            name='patientdoctormapping',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='patientdoctormapping',
            name='appointment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientdoctormapping',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor'),
        ),
        migrations.AlterField(
            model_name='patientdoctormapping',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.RemoveField(
            model_name='patientdoctormapping',
            name='assigned_by',
        ),
    ]
