# Generated by Django 4.2.7 on 2025-10-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={},
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='contact_number',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(max_length=100),
        ),
    ]
